### ISSUE TITLE
Chat Messages end with " ."

### ISSUE THREAD

**Issue by Flexios** [nhulston/ChatCore#12]
Please help, every Message ends with " ." (Space, dot). Its really annoying especally some Commands break because of that. I checked the Config and found nothing for it, disabling the Plugin gets rid of the " .". So it must be the Plugin please help

**Comment by nhulston** [comment]
Just change `add-period-enabled: true` to `add-period-enabled: false`
Also this setting only affects chat messages, it has nothing to do with commands
