### ISSUE TITLE
Hover Message

### ISSUE THREAD

**Issue by tomimza** [nhulston/ChatCore#16]
![image](https://user-images.githubusercontent.com/119277081/209418272-aef58552-c8a5-4207-aeaa-6159a27c6130.png)
 Hello, I want to know how to deactivate or modify that message when placing the mouse on the player

**Comment by nhulston** [comment]
This must be a separate plugin or a client-side mod you have. ChatCore doesn't have anything related to name history in the default config.
But if you added this to the config yourself, then please change `name-hover-enabled` in config to false
