### ISSUE TITLE
HEX doesnt work

### ISSUE THREAD

**Issue by kmai31e** [nhulston/ChatCore#19]
Paper 1.16.4, hex in Chat Core for java 8 doesnt work

**Comment by nhulston** [comment]
Can you post the section in your config.yml where you're trying to use HEX?

**Comment by kmai31e** [comment]
rank-formats:
  owner: ' &e&l♛ #1EF904OWNER &8| &f%name%: #1EF904%message%'

**Comment by kmai31e** [comment]
REF

**Comment by dustindinh-dev** [comment]
Any update?

**Comment by kmai31e** [comment]
........ @nhulston

**Comment by nhulston** [comment]
Fixed in the latest versions
