### ISSUE TITLE
Would you help me?

### ISSUE THREAD

**Issue by magicwendric** [nhulston/ChatCore#21]
_Hi,_
I have a minigames server and I would like to know if you can put a system where the chat is per world, for example, who is in the skywars world can only communicate with those who are in the skywars world... and who is in the world of skyblock can only communicate with skyblock world, and so on..
this would help me a lot, if you want to see how the server is doing... it's redegreen.mcnetwork.me

**Comment by nhulston** [comment]
Hello, sorry, this is quite a unique case that most servers wouldn't need, so I don't want to clutter up the plugin.
I recommend hosting each minigame on a separate server and creating a network. It will actually help your server run better since each minigame can run on its own thread.
