### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by Pl0psaMC** [nhulston/ChatCore#24]
Meanwhile, tried every possible way to apply a gradient, any idea what the right method is for this plugin? 

This one I tried:

```
<#RRGGBB>Text</#RRGGBB>
{#RRGGBB>}Text{#RRGGBB<}
<$#RRGGBB>Text<$#RRGGBB>
<gradient:#RRGGBB:#RRGGBB>Text</gradient>
```

Thanks in advance

**Comment by nhulston** [comment]
Thanks for opening. Gradient has been added in this format:
`<#RRGGBB>Text</#RRGGBB>`
https://www.spigotmc.org/resources/chat-core-manage-control-format-your-chat-chat-hovering-click-events-and-more.97447/update?update=516428
