### ISSUE TITLE
OP's have silentjoin/no join message

### ISSUE THREAD

**Issue by LegitDan** [nhulston/ChatCore#27]
I've looked around into all the other plugins i have, but found out that Chatcore somehow disables the Join message for OP's. It does work fine with non-OPs. i couldnt find anything in the config tho

**Comment by nhulston** [comment]
Thanks, fixed in https://www.spigotmc.org/resources/chat-core-manage-control-format-your-chat-chat-hovering-click-events-and-more.97447/update?update=516428 !
