### ISSUE TITLE
Not loading on Arclight Hybrid

### ISSUE THREAD

**Issue by SirDoof** [nhulston/ChatCore#3]
Hey! I've been excited to try out the plugin but it doesn't load on Arclight 1.16.5. Is it supposed to work with this/any hybrid or is it an issue with Arclight?
Here's the error: https://pastebin.com/shR9XV9m

**Comment by nhulston** [comment]
Hello, sorry for the late response.
Can you update the pastebin? The link currently says expired.
Thanks

**Comment by SirDoof** [comment]
Hi, I downloaded the latest version and it has loaded properly now, thanks!
If any other issue arises, I'll let you know.
