### ISSUE TITLE
new line in other things than automatic broadcasts

### ISSUE THREAD

**Issue by JedynyTakiPsiak** [nhulston/ChatCore#31]
haj o/
can i please to add/fix adding %newline% on everything with ''?
cause when i have eg. this with simple nice look auto announce
![image](https://github.com/nhulston/ChatCore/assets/46937966/310f7418-ee74-4d23-9c23-2f96aca6424b)
then i have this xD
![image](https://github.com/nhulston/ChatCore/assets/46937966/eb3b946e-ce48-4d6c-a3a7-12119aeea166)
I tried add %newline% but do nothing. 
Pls add this to everything, this will correct many visual things :>

**Comment by nhulston** [comment]
Added in the latest version!
https://www.spigotmc.org/resources/chat-core-manage-control-format-your-chat-chat-hovering-click-events-and-more.97447/update?update=516428
