### ISSUE TITLE
Clear chat message recipients instead of cancelling the event

### ISSUE THREAD

**Issue by Dinty1** [nhulston/ChatCore#4]
Cancelling the chat message prevents plugins like DiscordSRV from relaying it.

**Comment by nhulston** [comment]
Can you be more specific? I'm having trouble understanding what you mean. Are you referring to /chat clear?

**Comment by Dinty1** [comment]
Instead of doing `event.setCancelled(true)`, you can do `event.getRecipients().clear()`

**Comment by nhulston** [comment]
I have fixed this in the latest update. Thanks for opening this issue!
