### ISSUE TITLE
My chat filter is not working...

### ISSUE THREAD

**Issue by Coulexx** [nhulston/ChatCore#46]
Hello! I l have been having some issues with the chat filter, when someone tries to say a word like "associated" "as soon" and many more, the word gets blocked and the player gets muted even tho what he said was not wrong. I have been trying to fix that but it doesnt seem to work, if anyone could help me with that i would appreciate it!

**Comment by nhulston** [comment]
Please read the full config, you've configured it incorrectly

**Comment by Coulexx** [comment]
Ohh... I have been trying to fix it but it doesn't seem to work... I will send a picture of the config would you be able tell me what i need to do to make it work? Thank you! (The blurred words are the bad words by the way)
![20240415_025102](https://github.com/nhulston/ChatCore/assets/166681211/a97181a4-5b8d-4cdb-8036-364438dd4cce)
![20240415_025117](https://github.com/nhulston/ChatCore/assets/166681211/8577ceb4-bc43-4c09-b8d1-013fef362e6e)

**Comment by nhulston** [comment]
Yes, so notice how under `blocked-words-punishments` it says under `severe` it has the punishment `mute %player%...`.

You can update the punishment for the severe category to remove the mute command. Or you can just remove the `, severe` after each blocked word if you don't want to run any commands.

Also, there's another section in the config if you only want to block words like `ass` without blocking words like `associated`. Please read the config and Spigot page thoroughly and it should be clear how to setup the config to get what you want
