### ISSUE TITLE
Colon after username with chat mention

### ISSUE THREAD

**Issue by sudothefox** [nhulston/ChatCore#5]
A colon is appended to the end of a username that is highlighted with the chat mention feature, and this is not configurable. This doesn't look right if the username is mentioned in the middle, or end, of a message.

Solutions:
- Config option to disable the colon entirely
- Config option to only highlight a mentioned username if it's at the beginning of a message?

**Comment by nhulston** [comment]
Thanks for opening this issue.

I can't seem to replicate the issue, can you give some more information and a screenshot?
